services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.18.2
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    restart: unless-stopped